name: instaclone
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  eva_icons_flutter: ^3.1.0
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  device_info_plus: ^9.1.2
  mobile_device_identifier: ^0.0.2
  firebase_storage: ^11.2.4
  url_launcher: ^6.2.6
  curved_labeled_navigation_bar: ^2.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/fonts/


  fonts:
      - family: Powerpunchy
        fonts:
          - asset: assets/fonts/Powerpunchy.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
